- repo: git@github.com:litphp/pre-commit-php.git
  sha: 0f011f8
  hooks:
    - id: php-cbf
      files: \.(php)$
    - id: php-cs
      files: \.(php)$
    - id: php-unit
      files: \.(php)$
    - id: php-stan
      files: \.(php)$
